
# Site settings
title: Rebble Help
# email: your-email@domain.com
description: >
  Rebble Support Center, for any and all issues with your Pebble smartwatch
baseurl: ""		# no trailing slash
url: ""	# no trailing slash
excerpt_separator: <!--more-->

about: >
  TODO
twitter_username:    pebble_dev
github_username:     pebble-dev

# Build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
  sass_dir: _scss
  style: compressed

plugins:
- jemoji

collections: 
  topic:
    output: true
    permalink: /:collection/:path/